# Generated by Django 5.1.7 on 2025-03-17 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('position', models.CharField(default='Unknown', max_length=20)),
                ('best_position', models.CharField(default='Unknown', max_length=20)),
                ('max_rating', models.IntegerField(default=0)),
                ('base_rating', models.IntegerField(default=0)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('playing_style', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=18)),
                ('foot', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], default='Right', max_length=10)),
                ('offensive_awareness', models.IntegerField(default=0)),
                ('ball_control', models.IntegerField(default=0)),
                ('dribbling', models.IntegerField(default=0)),
                ('tight_possession', models.IntegerField(default=0)),
                ('low_pass', models.IntegerField(default=0)),
                ('lofted_pass', models.IntegerField(default=0)),
                ('finishing', models.IntegerField(default=0)),
                ('heading', models.IntegerField(default=0)),
                ('place_kicking', models.IntegerField(default=0)),
                ('curl', models.IntegerField(default=0)),
                ('defensive_awareness', models.IntegerField(default=0)),
                ('defensive_engagement', models.IntegerField(default=0)),
                ('tackling', models.IntegerField(default=0)),
                ('aggression', models.IntegerField(default=0)),
                ('goalkeeping', models.IntegerField(default=0)),
                ('gk_catching', models.IntegerField(default=0)),
                ('gk_parrying', models.IntegerField(default=0)),
                ('gk_reflexes', models.IntegerField(default=0)),
                ('gk_reach', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('acceleration', models.IntegerField(default=0)),
                ('kicking_power', models.IntegerField(default=0)),
                ('jump', models.IntegerField(default=0)),
                ('physical_contact', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('stamina', models.IntegerField(default=0)),
                ('weak_foot_usage', models.IntegerField(default=0)),
                ('weak_foot_accuracy', models.IntegerField(default=0)),
                ('form', models.IntegerField(default=0)),
                ('injury_resistance', models.IntegerField(default=0)),
                ('skills', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_player1', to='players.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_player2', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('players', models.ManyToManyField(related_name='squads', to='players.player')),
            ],
        ),
    ]
